### ISSUE TITLE
Request to update the code

### ISSUE THREAD

**Issue by abdulkalam07863** [pannet1/renko-super#7]
Hello Bro Kartik

Please update the code for BankNifty.py when run the code, it place orders only when signals came, else no orders to be placed either side,

**Comment by pannet1** [comment]
This is for positional trades. So first we want close open positions immediately, if it is in the opposite direction. 

there is nothing to fix here.  please feel free to modify as you wish or hire a developer to do it for you.

**Comment by abdulkalam07863** [comment]
Hi bro, 

I am just worried about, when anytime, big movements comes, there is shadows price movements, on charts, like supertrend level is 430 and price is 450, and price going down below the supertrend with good movements, bricks not creates just price moves, how to handle this ? Can you give any solution on this ?

**Comment by pannet1** [comment]
renko were created to remove visual noise. if you can't take the risk of big brick size, reduce brick size. downside is you will get lot trades and whipsaws. if you cant take even smaller risk then go for call spreads and put spreads.
